package com.mybatis.example.demomybatis.tables.test.dao.arajuladevi;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.mybatis.example.demomybatis.tables.test.model.arajuladevi.CUSTOMERS;
import com.mybatis.example.demomybatis.tables.test.model.arajuladevi.CUSTOMERSExample;

public interface CUSTOMERSMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARAJULADEVI.CUSTOMERS
     *
     * @mbg.generated Thu May 03 09:54:59 PDT 2018
     */
    long countByExample(CUSTOMERSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARAJULADEVI.CUSTOMERS
     *
     * @mbg.generated Thu May 03 09:54:59 PDT 2018
     */
    int deleteByExample(CUSTOMERSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARAJULADEVI.CUSTOMERS
     *
     * @mbg.generated Thu May 03 09:54:59 PDT 2018
     */
    int deleteByPrimaryKey(Long CUSTOMER_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARAJULADEVI.CUSTOMERS
     *
     * @mbg.generated Thu May 03 09:54:59 PDT 2018
     */
    int insert(CUSTOMERS record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARAJULADEVI.CUSTOMERS
     *
     * @mbg.generated Thu May 03 09:54:59 PDT 2018
     */
    int insertSelective(CUSTOMERS record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARAJULADEVI.CUSTOMERS
     *
     * @mbg.generated Thu May 03 09:54:59 PDT 2018
     */
    List<CUSTOMERS> selectByExample(CUSTOMERSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARAJULADEVI.CUSTOMERS
     *
     * @mbg.generated Thu May 03 09:54:59 PDT 2018
     */
    CUSTOMERS selectByPrimaryKey(Long CUSTOMER_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARAJULADEVI.CUSTOMERS
     *
     * @mbg.generated Thu May 03 09:54:59 PDT 2018
     */
    int updateByExampleSelective(@Param("record") CUSTOMERS record, @Param("example") CUSTOMERSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARAJULADEVI.CUSTOMERS
     *
     * @mbg.generated Thu May 03 09:54:59 PDT 2018
     */
    int updateByExample(@Param("record") CUSTOMERS record, @Param("example") CUSTOMERSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARAJULADEVI.CUSTOMERS
     *
     * @mbg.generated Thu May 03 09:54:59 PDT 2018
     */
    int updateByPrimaryKeySelective(CUSTOMERS record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARAJULADEVI.CUSTOMERS
     *
     * @mbg.generated Thu May 03 09:54:59 PDT 2018
     */
    int updateByPrimaryKey(CUSTOMERS record);
}