package com.mybatis.example.demomybatis.tables.test.model.arajuladevi;

public class CUSTOMERS {
    /**
     *com.mybatis.example.demomybatis.tables.
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARAJULADEVI.CUSTOMERS.CUSTOMER_ID
     *
     * @mbg.generated Thu May 03 09:54:59 PDT 2018
     */
    private Long CUSTOMER_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARAJULADEVI.CUSTOMERS.CUSTOMER_NAME
     *
     * @mbg.generated Thu May 03 09:54:59 PDT 2018
     */
    private String CUSTOMER_NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARAJULADEVI.CUSTOMERS.ZIP_CODE
     *
     * @mbg.generated Thu May 03 09:54:59 PDT 2018
     */
    private String ZIP_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARAJULADEVI.CUSTOMERS.CUSTOMER_ID
     *
     * @return the value of ARAJULADEVI.CUSTOMERS.CUSTOMER_ID
     *
     * @mbg.generated Thu May 03 09:54:59 PDT 2018
     */
    public Long getCUSTOMER_ID() {
        return CUSTOMER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARAJULADEVI.CUSTOMERS.CUSTOMER_ID
     *
     * @param CUSTOMER_ID the value for ARAJULADEVI.CUSTOMERS.CUSTOMER_ID
     *
     * @mbg.generated Thu May 03 09:54:59 PDT 2018
     */
    public void setCUSTOMER_ID(Long CUSTOMER_ID) {
        this.CUSTOMER_ID = CUSTOMER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARAJULADEVI.CUSTOMERS.CUSTOMER_NAME
     *
     * @return the value of ARAJULADEVI.CUSTOMERS.CUSTOMER_NAME
     *
     * @mbg.generated Thu May 03 09:54:59 PDT 2018
     */
    public String getCUSTOMER_NAME() {
        return CUSTOMER_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARAJULADEVI.CUSTOMERS.CUSTOMER_NAME
     *
     * @param CUSTOMER_NAME the value for ARAJULADEVI.CUSTOMERS.CUSTOMER_NAME
     *
     * @mbg.generated Thu May 03 09:54:59 PDT 2018
     */
    public void setCUSTOMER_NAME(String CUSTOMER_NAME) {
        this.CUSTOMER_NAME = CUSTOMER_NAME == null ? null : CUSTOMER_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARAJULADEVI.CUSTOMERS.ZIP_CODE
     *
     * @return the value of ARAJULADEVI.CUSTOMERS.ZIP_CODE
     *
     * @mbg.generated Thu May 03 09:54:59 PDT 2018
     */
    public String getZIP_CODE() {
        return ZIP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARAJULADEVI.CUSTOMERS.ZIP_CODE
     *
     * @param ZIP_CODE the value for ARAJULADEVI.CUSTOMERS.ZIP_CODE
     *
     * @mbg.generated Thu May 03 09:54:59 PDT 2018
     */
    public void setZIP_CODE(String ZIP_CODE) {
        this.ZIP_CODE = ZIP_CODE == null ? null : ZIP_CODE.trim();
    }
}